# Generated by Django 5.1.5 on 2025-01-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_category_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduserinfo',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adduserinfo',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
