# Generated by Django 5.1.5 on 2025-01-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_adduserinfo_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduserinfo',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='adduserinfo',
            name='is_locked',
        ),
    ]
