# Generated by Django 5.1.5 on 2025-01-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_adduserinfo_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduserinfo',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
