# Generated by Django 5.1.5 on 2025-01-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_adduserinfo_failed_login_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='writer',
        ),
        migrations.DeleteModel(
            name='AddUserInfo',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
